version: "3.8"

services:
  backend:
    image: ghcr.io/suwa-sh/gitlab-bud-chart/backend:latest
    container_name: gitlab-bud-chart-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/suwa-sh/gitlab-bud-chart/frontend:latest
    container_name: gitlab-bud-chart-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
