version: "3.8"

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: gitlab-bud-chart-nginx
    ports:
      - "${SERVER_PORT:-8081}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/nginx-health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ghcr.io/suwa-sh/gitlab-bud-chart/backend:latest
    container_name: gitlab-bud-chart-backend
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - GITLAB_SSL_VERIFY=${GITLAB_SSL_VERIFY:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/suwa-sh/gitlab-bud-chart/frontend:latest
    container_name: gitlab-bud-chart-frontend
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_GITLAB_URL=${VITE_GITLAB_URL}
      - VITE_GITLAB_TOKEN=${VITE_GITLAB_TOKEN}
      - VITE_GITLAB_PROJECT_ID=${VITE_GITLAB_PROJECT_ID}
      - VITE_HTTP_PROXY=${HTTP_PROXY}
      - VITE_HTTPS_PROXY=${HTTPS_PROXY}
      - VITE_NO_PROXY=${NO_PROXY}
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
