services:
  # Self-hosting GitLab CEをE2Eテスト用に追加
  gitlab:
    image: gitlab/gitlab-ce:17.9.2-ce.0
    container_name: gitlab
    ports:
      - "8080:80"
    volumes:
      - gitlab_e2e_config:/etc/gitlab
      - gitlab_e2e_logs:/var/log/gitlab
      - gitlab_e2e_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8080'
        # 初期セットアップの簡略化 - 一般的な文字の組み合わせだとエラーになる...
        gitlab_rails['initial_root_password'] = 'GLbudChart'
        # 起動時間短縮のための設定
        gitlab_rails['env'] = {'GITLAB_DISABLE_JEMALLOC' => 'true'}
        puma['worker_processes'] = 1
        sidekiq['max_concurrency'] = 10
        prometheus_monitoring['enable'] = false
        nginx['listen_port'] = 80

volumes:
  gitlab_e2e_config:
  gitlab_e2e_logs:
  gitlab_e2e_data:
